/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.udea.tecnicas.view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sofito-Chan
 */
public class Gui01 extends javax.swing.JFrame {
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Gui01
     */
    public Gui01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        registerStudentBT = new javax.swing.JButton();
        searchStudentBt = new javax.swing.JButton();
        updateDeleteStudentBT = new javax.swing.JButton();
        exitBT = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lastNamesTF = new javax.swing.JTextField();
        genderCB = new javax.swing.JComboBox<>();
        idTF = new javax.swing.JTextField();
        groupCB = new javax.swing.JComboBox<>();
        backMenu0BT = new javax.swing.JButton();
        registerBT = new javax.swing.JButton();
        ageTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        firstNamesTF = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        searchOptionCB = new javax.swing.JComboBox<>();
        searchBT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        backMenu1BT = new javax.swing.JButton();
        infoBT = new javax.swing.JButton();
        idSeacrhTF = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        backMenu2BT = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        idSearchUpdateTF = new javax.swing.JTextField();
        updateSearchBT = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        firstNamesUpdateTF = new javax.swing.JTextField();
        lastNamesUpdateTF = new javax.swing.JTextField();
        ageUpdateTF = new javax.swing.JTextField();
        idUpdateTF = new javax.swing.JTextField();
        updateStudentBT = new javax.swing.JButton();
        genderUpdateCB = new javax.swing.JComboBox<>();
        groupUpdateCB = new javax.swing.JComboBox<>();
        deleteStudentBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(200, 200, 200));
        MainPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        MainPanel.setEnabled(false);
        MainPanel.setFocusable(false);
        MainPanel.setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Matricula Estudiantil");

        registerStudentBT.setText("Matricular Estudiante");
        registerStudentBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerStudentBTActionPerformed(evt);
            }
        });

        searchStudentBt.setText("Buscar Estudiante");
        searchStudentBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentBtActionPerformed(evt);
            }
        });

        updateDeleteStudentBT.setText("Actualizar/borrar estudiante");
        updateDeleteStudentBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeleteStudentBTActionPerformed(evt);
            }
        });

        exitBT.setText("Salir");
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });

        jLabel11.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum orci ante, lacinia nec erat et");

        jLabel12.setText("Que desea hacer?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(183, 183, 183))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(exitBT)
                                .addGap(232, 232, 232))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updateDeleteStudentBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchStudentBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(179, 179, 179))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(registerStudentBT, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(registerStudentBT)
                .addGap(18, 18, 18)
                .addComponent(searchStudentBt)
                .addGap(18, 18, 18)
                .addComponent(updateDeleteStudentBT)
                .addGap(39, 39, 39)
                .addComponent(exitBT)
                .addContainerGap())
        );

        MainPanel.addTab("Menu", jPanel1);

        jPanel2.setEnabled(false);
        jPanel2.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Matricular Estudiante");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombres");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Apellidos");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Genero    ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Identificacion");

        jLabel7.setText("Grupo");

        lastNamesTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNamesTFKeyTyped(evt);
            }
        });

        genderCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "M", "F" }));

        idTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTFKeyTyped(evt);
            }
        });

        groupCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Primero", "Segundo", "Tercero", "Cuarto", "Quinto", " " }));

        backMenu0BT.setText("Volver al Menu");
        backMenu0BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenu0BTActionPerformed(evt);
            }
        });

        registerBT.setText("Matricular");
        registerBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBTActionPerformed(evt);
            }
        });

        ageTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageTFKeyTyped(evt);
            }
        });

        jLabel10.setText("Edad");

        firstNamesTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNamesTFKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(backMenu0BT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(registerBT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastNamesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNamesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(groupCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderCB, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lastNamesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(firstNamesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(groupCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backMenu0BT)
                    .addComponent(registerBT))
                .addContainerGap())
        );

        MainPanel.addTab("Matricular", jPanel2);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Buscar estudiante");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Buscar por:");

        searchOptionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Identificacion", " " }));

        searchBT.setText("Buscar");
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });

        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombres", "Apellidos", "Edad", "Identificacion", "Genero", "Grupo", "# Matricula"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentsTable);
        if (studentsTable.getColumnModel().getColumnCount() > 0) {
            studentsTable.getColumnModel().getColumn(0).setResizable(false);
            studentsTable.getColumnModel().getColumn(1).setResizable(false);
            studentsTable.getColumnModel().getColumn(2).setResizable(false);
            studentsTable.getColumnModel().getColumn(3).setResizable(false);
            studentsTable.getColumnModel().getColumn(4).setResizable(false);
            studentsTable.getColumnModel().getColumn(5).setResizable(false);
            studentsTable.getColumnModel().getColumn(6).setResizable(false);
        }

        backMenu1BT.setText("Volver al menu");
        backMenu1BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenu1BTActionPerformed(evt);
            }
        });

        infoBT.setText("?");
        infoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBTActionPerformed(evt);
            }
        });

        idSeacrhTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idSeacrhTFKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchOptionCB, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(infoBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchBT, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(194, 194, 194))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(backMenu1BT))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(idSeacrhTF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(searchOptionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBT)
                    .addComponent(infoBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(idSeacrhTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backMenu1BT)
                .addContainerGap())
        );

        MainPanel.addTab("Buscar", jPanel5);

        backMenu2BT.setText("Volver al menú");
        backMenu2BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenu2BTActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Actualizar estudiante");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Ingrese el numero de identificacion del estudiante: ");

        idSearchUpdateTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idSearchUpdateTFKeyTyped(evt);
            }
        });

        updateSearchBT.setText("Buscar");
        updateSearchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSearchBTActionPerformed(evt);
            }
        });

        jLabel15.setText("Inforcacion del estudiante");

        jLabel16.setText("Nombres");

        jLabel17.setText("Apellidos");

        jLabel18.setText("Edad");

        jLabel19.setText("Identificacion");

        jLabel20.setText("Genero");

        jLabel21.setText("Grupo");

        firstNamesUpdateTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNamesUpdateTFKeyTyped(evt);
            }
        });

        lastNamesUpdateTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNamesUpdateTFKeyTyped(evt);
            }
        });

        ageUpdateTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageUpdateTFKeyTyped(evt);
            }
        });

        idUpdateTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idUpdateTFKeyTyped(evt);
            }
        });

        updateStudentBT.setText("Realizar cambios");
        updateStudentBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentBTActionPerformed(evt);
            }
        });

        genderUpdateCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "M", "F" }));

        groupUpdateCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Primero", "Segundo", "Tercero", "Cuarto", "Quinto" }));

        deleteStudentBT.setText("Borrar");
        deleteStudentBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idSearchUpdateTF)
                        .addGap(34, 34, 34)
                        .addComponent(updateSearchBT))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(backMenu2BT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateStudentBT))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(firstNamesUpdateTF))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ageUpdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lastNamesUpdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(143, 143, 143)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(deleteStudentBT)
                                .addGap(29, 29, 29)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idUpdateTF)
                            .addComponent(genderUpdateCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(groupUpdateCB, 0, 115, Short.MAX_VALUE))))
                .addGap(47, 47, 47))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(idSearchUpdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateSearchBT))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(idUpdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(genderUpdateCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(groupUpdateCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(firstNamesUpdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(lastNamesUpdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(ageUpdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backMenu2BT)
                    .addComponent(updateStudentBT)
                    .addComponent(deleteStudentBT))
                .addGap(20, 20, 20))
        );

        MainPanel.addTab("Actualizar / Borrar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Navegacion Menu
    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBTActionPerformed

    private void updateDeleteStudentBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeleteStudentBTActionPerformed
        MainPanel.setSelectedIndex(3);
    }//GEN-LAST:event_updateDeleteStudentBTActionPerformed

    private void searchStudentBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentBtActionPerformed
        MainPanel.setSelectedIndex(2);
    }//GEN-LAST:event_searchStudentBtActionPerformed

    private void registerStudentBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerStudentBTActionPerformed
        MainPanel.setSelectedIndex(1);
    }//GEN-LAST:event_registerStudentBTActionPerformed

    //Botones para volver al menu
    private void backMenu0BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenu0BTActionPerformed
        MainPanel.setSelectedIndex(0);
    }//GEN-LAST:event_backMenu0BTActionPerformed

    private void backMenu1BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenu1BTActionPerformed
        MainPanel.setSelectedIndex(0);
    }//GEN-LAST:event_backMenu1BTActionPerformed

    private void backMenu2BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenu2BTActionPerformed
        MainPanel.setSelectedIndex(0);
    }//GEN-LAST:event_backMenu2BTActionPerformed

    //Restricciones de campos de texto "Matricular"
    private void firstNamesTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNamesTFKeyTyped
        if(!Character.isLetter(evt.getKeyChar()) & !(evt.getKeyChar()==KeyEvent.VK_SPACE) & !(evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_firstNamesTFKeyTyped

    private void lastNamesTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNamesTFKeyTyped
        if(!Character.isLetter(evt.getKeyChar()) & !(evt.getKeyChar()==KeyEvent.VK_SPACE) & !(evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_lastNamesTFKeyTyped

    private void ageTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTFKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        } 
    }//GEN-LAST:event_ageTFKeyTyped

    private void idTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTFKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        } 
    }//GEN-LAST:event_idTFKeyTyped
    
    //Boton matricular
    private void registerBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBTActionPerformed
        //Se comprueba que todos los campos no esten vacion, si se da el caso se informa al usuario
        if((firstNamesTF.getText().replace(" ", "").equals("") ) || (lastNamesTF.getText().replace(" ", "").equals("") ) || (ageTF.getText().replace(" ", "").equals("") ) || (idTF.getText().replace(" ", "").equals("")) || (String.valueOf(genderCB.getSelectedItem()).equals(" "))|| (String.valueOf(groupCB.getSelectedItem()).equals(" ")) ){
            JOptionPane.showMessageDialog(null, "Todos los campos debes ser llenados");
        }
        //Si todos los campos estan llenos, Se continua con el proceso
        else{
            String firstNames = firstNamesTF.getText();
            String lastNames = lastNamesTF.getText();
            String age = ageTF.getText();
            String id = idTF.getText();
            String group = String.valueOf(groupCB.getSelectedItem());
            String gender = String.valueOf(genderCB.getSelectedItem());
            //Asignar datos ingresados a un estudiante
           
            //Se limpian los campos de texto
            firstNamesTF.setText("");
            lastNamesTF.setText("");
            ageTF.setText("");
            idTF.setText("");
            genderCB.setSelectedIndex(0);
            groupCB.setSelectedIndex(0);
            
            //se informa que la operacion ha sido exitosa
            JOptionPane.showMessageDialog(null, "Se ha matricula con exito al estudiante");
        }
    }//GEN-LAST:event_registerBTActionPerformed

    //boton de informacion para el usuario a la hora de buscar
    private void infoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBTActionPerformed
        JOptionPane.showMessageDialog(null, "Si desea Ver el listado de todos los estudiante seleccione"
                                            + " \"Todos\" y oprima el boton buscar.\n"
                                            + "Si lo que desea es buscar a un estudiante en especifico\n"
                                            + "seleccione \"Identificacion\", ingrese el numero de identificacion"
                                            + " y oprima el boton buscar.  ");
    }//GEN-LAST:event_infoBTActionPerformed

    //Restricciones para el campo de texto en la pestaña "Buscar"
    private void idSeacrhTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idSeacrhTFKeyTyped
        if(String.valueOf(searchOptionCB.getSelectedItem()).equals("Todos")){
            evt.consume();
        }
        else if((String.valueOf(searchOptionCB.getSelectedItem()).equals("Identificacion"))&&(!Character.isDigit(evt.getKeyChar()))){
            evt.consume();
        }
    }//GEN-LAST:event_idSeacrhTFKeyTyped
    
    //Boton "Buscar" pestaña "Buscar"
    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
        if(String.valueOf(searchOptionCB.getSelectedItem()).equals("Todos")){
            //mostrar todos los estudiantes en la tabla
        }
        else if(String.valueOf(searchOptionCB.getSelectedItem()).equals("identificacion")){
            //Se comprueba que el campo de texto no este vacio a la hora de buscar
            if(idSeacrhTF.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Ingrese la identificacion del estudiante\n para realizar a busqueda");
            }
            else{
                //mostrar estudiante con la identificacion Ingresada 
                
                //se limpia el campo de texto
                idSeacrhTF.setText("");
            }
        }
    }//GEN-LAST:event_searchBTActionPerformed
    
    //Restricciones para los campos de texto de "Actualizar estudiante"
    private void idSearchUpdateTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idSearchUpdateTFKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_idSearchUpdateTFKeyTyped

    private void firstNamesUpdateTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNamesUpdateTFKeyTyped
        if(!Character.isLetter(evt.getKeyChar()) & !(evt.getKeyChar()==KeyEvent.VK_SPACE) & !(evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_firstNamesUpdateTFKeyTyped

    private void lastNamesUpdateTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNamesUpdateTFKeyTyped
        if(!Character.isLetter(evt.getKeyChar()) & !(evt.getKeyChar()==KeyEvent.VK_SPACE) & !(evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_lastNamesUpdateTFKeyTyped

    private void ageUpdateTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageUpdateTFKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_ageUpdateTFKeyTyped

    private void idUpdateTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idUpdateTFKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_idUpdateTFKeyTyped

    //Boton "Buscar" en la pestaña "Actualizar/Borrar"
    private void updateSearchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSearchBTActionPerformed
        if(idSearchUpdateTF.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debe ingresar un documento para poder buscar");
        }
        else{
            //Buscar estudiante y asignar informacion a variables
            String currentNames = "Current Names";
            String currentLastNames = "Current Last Names";
            String currentAge = "Current Age";
            String currentId = "Current Id";
            
            //Se muestra la informacion que se tiene del estudiante
            firstNamesUpdateTF.setText(currentNames);
            lastNamesUpdateTF.setText(currentLastNames);
            ageUpdateTF.setText(currentAge);
            idUpdateTF.setText(currentId);
            genderUpdateCB.setSelectedIndex(0);
            groupUpdateCB.setSelectedIndex(0);
        }
        
        
        
    }//GEN-LAST:event_updateSearchBTActionPerformed
    
    //Boton "Borrar" pestaña "Actualizar/Borrar"
    private void deleteStudentBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentBTActionPerformed
        if(idSearchUpdateTF.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debes ingresar un numero de identificacion para borrar a un estudiante");
        }
        else{
            String idStudentDeleted = idSearchUpdateTF.getText();
            //Borrar estudiante con la id ingresada
            
            //se informa de que qla operacion se ha realizado
            JOptionPane.showMessageDialog(null, "Se ha borrado con exito al estudiante");
        }
    }//GEN-LAST:event_deleteStudentBTActionPerformed

    //Boton "Realizar Cambios" pestaña "Actualizar/Borrar"
    private void updateStudentBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentBTActionPerformed
        if((firstNamesUpdateTF.getText().replace(" ", "").equals("") ) || (lastNamesUpdateTF.getText().replace(" ", "").equals("") ) || (ageUpdateTF.getText().equals("") ) || (idUpdateTF.getText().equals("")) || (String.valueOf(genderUpdateCB.getSelectedItem()).equals(" "))|| (String.valueOf(groupUpdateCB.getSelectedItem()).equals(" ")) ){
            JOptionPane.showMessageDialog(null, "Todos los campos debes ser llenados");
        }
        else{
            // se obtien la informacion actualizada del estudiante
            String newFirstNames = firstNamesUpdateTF.getText();
            String newlastsNames =lastNamesUpdateTF.getText();
            String newAge = ageUpdateTF.getText();
            String newId = idUpdateTF.getText();
            String newGender = String.valueOf(genderUpdateCB.getSelectedItem());
            String newGroup = String.valueOf(groupUpdateCB.getSelectedItem());
            
            //Actualizar estudiante con los datos ingresados
            
            //Se limpian los campos de texto
            idSearchUpdateTF.setText("");
            firstNamesUpdateTF.setText("");
            lastNamesUpdateTF.setText("");
            ageUpdateTF.setText("");
            idUpdateTF.setText("");
            
            //Se infroma que la operacion se han realizado 
            JOptionPane.showMessageDialog(null,"Se han actualizado con exito los datos");
        }
    }//GEN-LAST:event_updateStudentBTActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainPanel;
    private javax.swing.JTextField ageTF;
    private javax.swing.JTextField ageUpdateTF;
    private javax.swing.JButton backMenu0BT;
    private javax.swing.JButton backMenu1BT;
    private javax.swing.JButton backMenu2BT;
    private javax.swing.JButton deleteStudentBT;
    private javax.swing.JButton exitBT;
    private javax.swing.JTextField firstNamesTF;
    private javax.swing.JTextField firstNamesUpdateTF;
    private javax.swing.JComboBox<String> genderCB;
    private javax.swing.JComboBox<String> genderUpdateCB;
    private javax.swing.JComboBox<String> groupCB;
    private javax.swing.JComboBox<String> groupUpdateCB;
    private javax.swing.JTextField idSeacrhTF;
    private javax.swing.JTextField idSearchUpdateTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JTextField idUpdateTF;
    private javax.swing.JButton infoBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNamesTF;
    private javax.swing.JTextField lastNamesUpdateTF;
    private javax.swing.JButton registerBT;
    private javax.swing.JButton registerStudentBT;
    private javax.swing.JButton searchBT;
    private javax.swing.JComboBox<String> searchOptionCB;
    private javax.swing.JButton searchStudentBt;
    private javax.swing.JTable studentsTable;
    private javax.swing.JButton updateDeleteStudentBT;
    private javax.swing.JButton updateSearchBT;
    private javax.swing.JButton updateStudentBT;
    // End of variables declaration//GEN-END:variables
}
